### ISSUE TITLE
Progress area: no state if nothing todo

### ISSUE THREAD

**Issue by lightonflux** [Emersont1/big-finish-downloader#32]
![Bildschirmfoto von 2021-01-25 12-45-39](https://user-images.githubusercontent.com/1377943/105701967-60e79200-5f0b-11eb-88b8-7c8fcb8d436a.png)

So i think everything is downloaded (not much on the account). But in the progress area the progress bar is empty and the last item is still displayed.

If everything is downloaded, the progress area should display a message that everything is downloaded/synced.

**Comment by lightonflux** [comment]
Additionally, maybe auto collapse the download list, if it is empty. That way the user can see more of the "Downloaded" section.

**Comment by Emersont1** [comment]
> Additionally, maybe auto collapse the download list, if it is empty. That way the user can see more of the "Downloaded" section.

This may be achievable with a GtkExpander, but will need experimentation

**Comment by Emersont1** [comment]
https://github.com/Emersont1/big-finish-downloader/blob/d8e06015b919bbe93414ef3ca11af184577b956a/big-finish-downloader-gtk/src/gui/main_window/update_func.cpp#L56-L62

> If everything is downloaded, the progress area should display a message that everything is downloaded/synced.

I thought I'd already implemented that. Turns out I have, but Its not being called for some reason

**Comment by Emersont1** [comment]
> > Additionally, maybe auto collapse the download list, if it is empty. That way the user can see more of the "Downloaded" section.
> 
> This may be achievable with a GtkExpander, but will need experimentation

I've Tried doing this in #36 but I can't get a result I'm happy with, so I think this will have to be left
